baseURL: "https://www.mediaglasses.blog/"
title: "MediaGlasses"
paginate: "5"
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "UA-43497944-1"

permalinks:
  posts: "/:year/:month/:day/:title/"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "MediaGlasses"
  description: "Ramblings of a nerd"
  keywords: ["Blog", "Technical", "Automation", "DevOps"]
  author: "Russ McKendrick"
  images: ["/images/blog-cover.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: "auto" # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "images/logo.svg"

  label:
    text: "MediaGlasses"
    icon: "/images/logo.svg"
    iconHeight: 40

  socialIcons:
    - name: twitter
      url: "https://twitter.com/russmckendrick/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/russmckendrick/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    responsiveImages: true
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/russmckendrick/blog/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content"]

menu:
  main:
    - identifier: search
      url: /search/
      pre: <ion-icon name="search"></ion-icon>
      weight: 10
    - identifier: tags
      url: /tags/
      pre: <ion-icon name="pricetags"></ion-icon>
      weight: 20

    - identifier: twitter
      pre: <ion-icon name="logo-twitter"></ion-icon>
      url: https://twitter.com/russmckendrick/
      weight: 50
    - identifier: github
      pre: <ion-icon name="logo-github"></ion-icon>
      url: https://github.com/russmckendrick
      weight: 51
    - identifier: linkedin
      pre: <ion-icon name="logo-linkedin"></ion-icon>
      url: https://www.linkedin.com/in/russmckendrick/
      weight: 52
    # - identifier: docker
    #   pre: <ion-icon name="logo-docker"></ion-icon>
    #   url: https://hub.docker.com/u/russmckendrick/
    #   weight: 53
    - identifier: amazon
      pre: <ion-icon name="logo-amazon"></ion-icon>
      url: https://www.amazon.com/author/russmckendrick
      weight: 54
    # - identifier: instagram
    #   pre: <ion-icon name="logo-instagram"></ion-icon>
    #   url: https://www.instagram.com/russmckendrick/
    #   weight: 55
    # - identifier: medium
    #   pre: <ion-icon name="logo-medium"></ion-icon>
    #   url: https://russmckendrick.medium.com/
    #   weight: 56
    # - identifier: dicogs
    #   pre: <ion-icon name="disc"></ion-icon>
    #   url: https://records.mckendrick.page/
    #   weight: 57
    - identifier: about
      pre: <ion-icon name="earth"></ion-icon>
      url: https://russ.mckendrick.io/
      weight: 100

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
    - _redirects

disableAliases: true

mediaTypes:
  text/redirects:

outputFormats:
  _redirect:
    name: _redirects
    mediaType: text/redirects
    baseName: _redirects
    isPlainText: true
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: true
    style: monokai

ignoreErrors: ["error-remote-getjson", "error-missing-instagram-accesstoken"]
